testing out drupal config

diff --git a/web-build/Dockerfile.frankenphp b/web-build/Dockerfile.frankenphp
--- a/web-build/Dockerfile.frankenphp
+++ b/web-build/Dockerfile.frankenphp
@@ -1,12 +1,13 @@
 #ddev-generated
-ARG BASE_IMAGE
-FROM $BASE_IMAGE
-ENV FRANKENPHP_VERSION=v1.1.0
+#ARG BASE_IMAGE
+#FROM $BASE_IMAGE
 
-RUN curl --fail -L -o /usr/local/bin/frankenphp https://github.com/dunglas/frankenphp/releases/download/${FRANKENPHP_VERSION}/frankenphp-linux-$(uname -m) && \
-    chmod +x /usr/local/bin/frankenphp
+FROM dunglas/frankenphp:1.1.2-php8.3
+
+# add additional extensions here:
+RUN install-php-extensions pdo_mysql gd intl zip xml curl json openssl mbstring apcu readline opcache
 
 ENTRYPOINT ["/mnt/ddev_config/commands/web/frankenphp-ctl", "start"]
 
 # See if frankenphp is running
-HEALTHCHECK --interval=1s --timeout=120s --retries=1 --start-period=120s CMD ps -p $(cat /tmp/frankenphp.pid) > /dev/null; exit $?
+#HEALTHCHECK --interval=1s --timeout=120s --retries=1 --start-period=120s CMD ps -p $(cat /tmp/frankenphp.pid) > /dev/null; exit $?
